### PR TITLE
fix(RCTScrollView): Fix vertical scrolling behavior for RCTScrollView

### LINKED ISSUE #143: Implement ScrollViewManager functionality

### PR DESCRIPTION
**Pull request by rozele**
There is an issue with scroll view where the container view was being collapsed by the optimizer. Ensure the 'collapsable' property is picked up.

Fixes #143

### CODE REVIEW

File: Libraries/Components/ScrollView/ScrollView.js [hunk 1]
```diff
@@ -593,6 +595,8 @@ if (Platform.OS === 'android') {
   );
 } else if (Platform.OS === 'ios') {
   var RCTScrollView = requireNativeComponent('RCTScrollView', ScrollView);
+} else if (Platform.OS === 'windows') {
```
Comment (mpodwysocki) [inline Libraries/Components/ScrollView/ScrollView.js]: Do we want to collapse to a singe if statement here for iOS and Windows?

**Comment by mpodwysocki** [comment]
Other than collapsing the iOS and Windows to be the same, LGTM

File: Libraries/Components/ScrollView/ScrollView.js (hunk 1 above)
Comment (rozele) [inline Libraries/Components/ScrollView/ScrollView.js]: No, I want to keep the Windows specific stuff very explicitly isolated.  We may change the behavior later.
________________________________
